# Generated by Django 3.2.8 on 2021-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_tittle_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('age', models.IntegerField(default=10)),
                ('department', models.CharField(max_length=300)),
                ('course', models.TextField()),
                ('date_of_entry', models.DateTimeField()),
            ],
        ),
    ]
